Update ContainerCuttingTable.java
GTNewHorizons/WitchingGadgets pull request #35
Opened 2022-12-26 19:52 UTC by Shibva

wrapped aspect check inside of a check for CompoundTags; fixes the nullPointerException caused by putting in a phial that does not hold anything in it [a techicnal oversight on the original dev's part]

2022-12-26 21:23 UTC, glowredman requested changes

2022-12-26 21:23 UTC, glowredman commented on src/main/java/witchinggadgets/common/gui/ContainerCuttingTable.java
> +                                || stack.getItem().equals(ConfigItems.itemWispEssence)) {
```suggestion
                                || stack.getItem() == ConfigItems.itemWispEssence) {
```

2022-12-26 21:23 UTC, glowredman commented on src/main/java/witchinggadgets/common/gui/ContainerCuttingTable.java
> +                        if (stack.getItem().equals(ConfigItems.itemEssence)
```suggestion
                        if (stack.getItem() == ConfigItems.itemEssence
```

2022-12-26 21:23 UTC, glowredman commented on src/main/java/witchinggadgets/common/gui/ContainerCuttingTable.java
> +                        if (stack.getItem().equals(ConfigItems.itemEssence)
```suggestion
                        if (stack.getItem() == ConfigItems.itemEssence
```

2022-12-27 05:28 UTC, Shibva commented
I did the change as minimal to the code that was already present and that as just wrapping it, I knew there were probs a better way to optimize it but still getting my feet wet into this sort of thing; the changes look a lot better now. Using my current fix on my end and have not ran into any issues; if this is doing the same thing but more efficiently than thank you for improving it ^w^

2022-12-27 05:33 UTC, Shibva reviewed
improved from original and better methods present: as long as it wont accept  empty aspect continers in the aspect slots this should be sufficent, maybe more-so than the original

thanks :)

2022-12-27 05:34 UTC, Shibva commented
*empty containers

2022-12-27 23:07 UTC, glowredman approved these changes

2022-12-27 23:08 UTC, merged